import { LocalDb, Operation } from '../storage/db';

const BACKEND_URL = 'http://localhost:3000';

export interface SyncResult {
  success: boolean;
  pushedCount: number;
  pulledCount: number;
  error?: string;
}

export class SyncEngine {
  private static isSyncing = false;
  private static serverOnline = true; // starts assuming online

  static isServerOnline(): boolean {
    return this.serverOnline;
  }

  // Ping the server to check connectivity
  static async checkOnline(): Promise<boolean> {
    try {
      const controller = new AbortController();
      const id = setTimeout(() => controller.abort(), 2000); // 2 second timeout
      
      const response = await fetch(`${BACKEND_URL}/api/debug/stats`, {
        signal: controller.signal
      });
      clearTimeout(id);
      
      this.serverOnline = response.ok;
      return response.ok;
    } catch (err) {
      this.serverOnline = false;
      return false;
    }
  }

  // Run the full push/pull sync cycle
  static async sync(): Promise<SyncResult> {
    if (this.isSyncing) {
      return { success: false, pushedCount: 0, pulledCount: 0, error: 'Sync already in progress' };
    }

    this.isSyncing = true;
    let pushedCount = 0;
    let pulledCount = 0;

    try {
      const online = await this.checkOnline();
      if (!online) {
        throw new Error('Server offline');
      }

      const DEVICE_ID = LocalDb.getDeviceId();

      // 1. Push Phase: Gathers all unsynced operations
      const pendingOps = LocalDb.getPendingOperations();
      if (pendingOps.length > 0) {
        console.log(`[SyncEngine:${DEVICE_ID}] Pushing ${pendingOps.length} operations...`);
        
        const pushResponse = await fetch(`${BACKEND_URL}/sync/push`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ operations: pendingOps })
        });

        if (!pushResponse.ok) {
          throw new Error(`Push failed with status ${pushResponse.status}`);
        }

        const pushData = await pushResponse.json();
        if (pushData.success) {
          // Operations successfully merged on server, remove from local queue
          const pushedEventIds = pendingOps.map(op => op.eventId);
          await LocalDb.markOperationsSynced(pushedEventIds);
          pushedCount = pendingOps.length;
          console.log(`[SyncEngine:${DEVICE_ID}] Push completed. Mark ${pushedCount} operations as synced.`);
        }
      }

      // 2. Pull Phase: Pull operations from the server
      const lastSyncedVersion = LocalDb.getLastSyncedVersion();
      console.log(`[SyncEngine:${DEVICE_ID}] Pulling operations since server version: ${lastSyncedVersion}`);

      const pullResponse = await fetch(`${BACKEND_URL}/sync/pull?sinceVersion=${lastSyncedVersion}`);
      if (!pullResponse.ok) {
        throw new Error(`Pull failed with status ${pullResponse.status}`);
      }

      const pullData = (await pullResponse.json()) as {
        operations: Operation[];
        currentServerVersion: number;
      };

      // Filter out operations generated by this device to avoid double-processing
      const remoteOps = pullData.operations.filter(op => op.deviceId !== DEVICE_ID);

      if (remoteOps.length > 0) {
        console.log(`[SyncEngine:${DEVICE_ID}] Applying ${remoteOps.length} remote operations...`);
        await LocalDb.applyRemoteOperations(remoteOps);
        pulledCount = remoteOps.length;
      }

      // Update local synced version
      await LocalDb.setLastSyncedVersion(pullData.currentServerVersion);
      console.log(`[SyncEngine:${DEVICE_ID}] Sync successful. Updated lastSyncedVersion to ${pullData.currentServerVersion}`);

      this.isSyncing = false;
      return { success: true, pushedCount, pulledCount };
    } catch (err: any) {
      console.warn(`[SyncEngine] Sync failed: ${err.message}`);
      this.isSyncing = false;
      return { success: false, pushedCount, pulledCount, error: err.message };
    }
  }
}
